"""Ajustando bases

Revision ID: f6986b043aa8
Revises: 
Create Date: 2021-04-18 18:01:50.377382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6986b043aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_stock')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('id_stock', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
